spring:
  application:
    name: user-crud
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/user-crud?createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate.ddl-auto: update
    show-sql: true
